=== GergoSz/B5XVY_XMLgyak/XMLTaskB5XVY7/B5XVY7.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="lakcim">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="varos" type="xs:string"/>
        <xs:element name="utca" type="xs:string"/>
        <xs:element name="hazszam" type="xs:int"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="Pek">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nev" type="xs:string"/>
        <xs:element name="beosztas" type="xs:string"/>
        <xs:element ref="lakcim"/>
      </xs:sequence>
      <xs:attribute type="xs:int" name="szemszam" use="required"/>
      <xs:attribute type="xs:int" name="eszkoz" use="optional"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="PekPekseg">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute type="xs:int" name="pekszemszam" use="required"/>
          <xs:attribute type="xs:string" name="peksegnev" use="required"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="Pekseg">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="pcim" type="xs:string"/>
        <xs:element name="nyitas" type="xs:string"/>
      </xs:sequence>
      <xs:attribute type="xs:string" name="pnev" use="required"/>
    </xs:complexType>
  </xs:element>

  
  <xs:element name="Eszkoz">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="eszkoznev" type="xs:string"/>
        <xs:element name="allapot" type="xs:boolean"/>
      </xs:sequence>
      <xs:attribute type="xs:int" name="eszkozazon" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="Vevo">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="fizetett" type="xs:short"/>
        <xs:element name="kiszolgalta" type="xs:string"/>
      </xs:sequence>
      <xs:attribute type="xs:int" name="vevoszam" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="VevoTermek">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute type="xs:int" name="vevoszam" use="required"/>
          <xs:attribute type="xs:int" name="tkod" use="required"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="Termek">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="termeknev" type="xs:string"/>
        <xs:element name="sosedes" type="xs:int"/>
        <xs:element name="kesitesideje" type="xs:string"/>
      </xs:sequence>
      <xs:attribute type="xs:int" name="tkod" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="Vegzettseg">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="megnevezes" type="xs:string"/>
      </xs:sequence>
      <xs:attribute type="xs:string" name="ID" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="PekVegzettse">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute type="xs:int" name="szemszam" use="required"/>
          <xs:attribute type="xs:string" name="vegID" use="required"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="PekTermek">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute type="xs:int" name="szemszam" use="required"/>
          <xs:attribute type="xs:string" name="tkod" use="required"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="Pekek">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Pek" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="PekPeksegek">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="PekPekseg" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Peksegek">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Pekseg" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Eszkozok">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Eszkoz" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Vevok">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Vevo" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="VevoTermekek">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="VevoTermek" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Termekek">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Termek" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Vegzettsegek">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Vegzettseg" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="PekVegzettsegek">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="PekVegzettse" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="PekTermekek">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="PekTermek" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="root">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Pekek"/>
        <xs:element ref="PekPeksegek"/>
        <xs:element ref="Peksegek"/>
        <xs:element ref="Eszkozok"/>
        <xs:element ref="Vevok"/>
        <xs:element ref="VevoTermekek"/>
        <xs:element ref="Termekek"/>
        <xs:element ref="Vegzettsegek"/>
        <xs:element ref="PekVegzettsegek"/>
        <xs:element ref="PekTermekek"/>
      </xs:sequence>
    </xs:complexType>
    <xs:key name="szemszam">
      <xs:selector xpath="Pek"/>
      <xs:field xpath="@szemszam"/>
    </xs:key>
    <xs:key name="pnev">
      <xs:selector xpath="Pekseg"/>
      <xs:field xpath="@pnev"/>
    </xs:key>
    <xs:key name="eszkozazon">
      <xs:selector xpath="Eszkoz"/>
      <xs:field xpath="@eszkozazon"/>
    </xs:key>
    <xs:key name="vevoszam">
      <xs:selector xpath="Vevo"/>
      <xs:field xpath="@vevoszam"/>
    </xs:key>
    <xs:key name="tkod">
      <xs:selector xpath="Termek"/>
      <xs:field xpath="@tkod"/>
    </xs:key>
    <xs:key name="ID">
      <xs:selector xpath="Vevo"/>
      <xs:field xpath="@ID"/>
    </xs:key>
    <xs:keyref name="eszkoz" refer="eszkozazon">
      <xs:selector xpath="Pek"/>
      <xs:field xpath="@eszkoz"/>
    </xs:keyref>
    <xs:keyref name="pekszemszam" refer="szemszam">
      <xs:selector xpath="PekPekseg"/>
      <xs:field xpath="@szemszam"/>
    </xs:keyref>
    <xs:keyref name="peksegnev" refer="pnev">
      <xs:selector xpath="PekPekseg"/>
      <xs:field xpath="@pnev"/>
    </xs:keyref>
    <xs:keyref name="fkvevoszam" refer="vevoszam">
      <xs:selector xpath="VevoTermek"/>
      <xs:field xpath="@vevoszam"/>
    </xs:keyref>
    <xs:keyref name="fktkod" refer="tkod">
      <xs:selector xpath="VevoTermek"/>
      <xs:field xpath="@tkod"/>
    </xs:keyref>
    <xs:keyref name="fkvegzettsegszemszam" refer="szemszam">
      <xs:selector xpath="PekVegzettse"/>
      <xs:field xpath="@szemszam"/>
    </xs:keyref>
    <xs:keyref name="vegID" refer="ID">
      <xs:selector xpath="PekVegzettse"/>
      <xs:field xpath="@ID"/>
    </xs:keyref>
    <xs:keyref name="fkszemszam" refer="szemszam">
      <xs:selector xpath="PekTermek"/>
      <xs:field xpath="@szemszam"/>
    </xs:keyref>
    <xs:keyref name="fkpektermektkod" refer="tkod">
      <xs:selector xpath="PekTermek"/>
      <xs:field xpath="@tkod"/>
    </xs:keyref>
  </xs:element>
</xs:schema>

=== GergoSz/B5XVY_XMLgyak/XMLTaskB5XVY7/B5XVY7.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="B5XVY7.xsd">
    
    <Pekek>
        <Pek szemszam="12345" eszkoz="00">
            <nev>Amal</nev>
            <beosztas>Főpék</beosztas>
            <lakcim>
                <varos>Miskolc</varos>
                <utca>Eper</utca>
                <hazszam>2</hazszam>
            </lakcim>
        </Pek>
        <Pek szemszam="23456" eszkoz="05">
            <nev>Darius</nev>
            <beosztas>Cukrász</beosztas>
            <lakcim>
                <varos>Tiszaújváros</varos>
                <utca>Kossuth</utca>
                <hazszam>4</hazszam>
            </lakcim>
        </Pek>
        <Pek szemszam="34567" eszkoz="02">
            <nev>Benedict</nev>
            <beosztas>Pék</beosztas>
            <lakcim>
                <varos>Eger</varos>
                <utca>Weöres</utca>
                <hazszam>78</hazszam>
            </lakcim>
        </Pek>
        <Pek szemszam="45678" eszkoz="03">
            <nev>Barbara</nev>
            <beosztas>Cukrász</beosztas>
            <lakcim>
                <varos>Sátoraljaújhely</varos>
                <utca>Deák</utca>
                <hazszam>12</hazszam>
            </lakcim>
        </Pek>
    </Pekek>

    <PekPeksegek>
        <PekPekseg pekszemszam="45678" peksegnev="pekseg3" />
        <PekPekseg pekszemszam="34567" peksegnev="pekseg1" />
        <PekPekseg pekszemszam="23456" peksegnev="pekseg2" />
        <PekPekseg pekszemszam="12345" peksegnev="pekseg1" />
        <PekPekseg pekszemszam="23456" peksegnev="pekseg4" />

    </PekPeksegek>

    <Peksegek>
        <Pekseg pnev="pekseg1">
            <pcim>Kenyéten Hold utca 3</pcim>
            <nyitas>2008-02-07 07:56:12</nyitas>
        </Pekseg>
        <Pekseg pnev="pekseg2">
            <pcim>Eger Bartók Béla út 15/B</pcim>
            <nyitas>2018-09-21 08:05:08</nyitas>
        </Pekseg>
        <Pekseg pnev="pekseg3">
            <pcim>Miskolc Eper utca 3</pcim>
            <nyitas>2010-12-17 16:18:34</nyitas>
        </Pekseg>
        <Pekseg pnev="pekseg4">
            <pcim>Miskolc Ifjuság utca 5</pcim>
            <nyitas>2001-09-08 01:51:25</nyitas>
        </Pekseg>
    </Peksegek>
    
    <Eszkozok>
        <Eszkoz eszkozazon="00">
            <eszkoznev>Munkaasztallap</eszkoznev>
            <allapot>1</allapot>
        </Eszkoz>
        <Eszkoz eszkozazon="01">
            <eszkoznev>Szakajtó</eszkoznev>
            <allapot>0</allapot>
        </Eszkoz>
        <Eszkoz eszkozazon="02">
            <eszkoznev>Kuglófforma</eszkoznev>
            <allapot>1</allapot>
        </Eszkoz>
        <Eszkoz eszkozazon="03">
            <eszkoznev>Péklapát</eszkoznev>
            <allapot>0</allapot>
        </Eszkoz>
        <Eszkoz eszkozazon="04">
            <eszkoznev>Nyujtófa</eszkoznev>
            <allapot>1</allapot>
        </Eszkoz>
        <Eszkoz eszkozazon="05">
            <eszkoznev>Péklapát</eszkoznev>
            <allapot>1</allapot>
        </Eszkoz>
    </Eszkozok>

    <Vevok>
        <Vevo vevoszam="00">
            <fizetett>1200</fizetett>
            <kiszolgalta>Barbara</kiszolgalta>
        </Vevo>
        <Vevo vevoszam="01">
            <fizetett>2400</fizetett>
            <kiszolgalta>Amal</kiszolgalta>
        </Vevo>
        <Vevo vevoszam="02">
            <fizetett>5000</fizetett>
            <kiszolgalta>Darius</kiszolgalta>
        </Vevo>
        <Vevo vevoszam="03">
            <fizetett>200</fizetett>
            <kiszolgalta>Barbara</kiszolgalta>
        </Vevo>
    </Vevok>

    <VevoTermekek>
        <VevoTermek vevoszam="03" tkod="03" />
        <VevoTermek vevoszam="03" tkod="03" />
        <VevoTermek vevoszam="03" tkod="03" />
        <VevoTermek vevoszam="03" tkod="03" />
        <VevoTermek vevoszam="02" tkod="02" />
        <VevoTermek vevoszam="01" tkod="00" />
        <VevoTermek vevoszam="01" tkod="01" />
        <VevoTermek vevoszam="01" tkod="00" />
        <VevoTermek vevoszam="00" tkod="01" />

    </VevoTermekek>

    <Termekek>
        <Termek tkod="00">
            <termeknev>Kuglóf</termeknev>
            <sosedes>1</sosedes>
            <kesitesideje>22/Nov/2021</kesitesideje>
        </Termek>
        <Termek tkod="01">
            <termeknev>Kenyér</termeknev>
            <sosedes>0</sosedes>
            <kesitesideje>23/Nov/2021</kesitesideje>
        </Termek>
        <Termek tkod="02">
            <termeknev>Torta</termeknev>
            <sosedes>1</sosedes>
            <kesitesideje>23/Nov/2021</kesitesideje>
        </Termek>
        <Termek tkod="03">
            <termeknev>Zsemle</termeknev>
            <sosedes>0</sosedes>
            <kesitesideje>22/Nov/2021</kesitesideje>
        </Termek>
    </Termekek>

    <Vegzettsegek>
        <Vegzettseg ID="veg1">
            <megnevezes>Pék</megnevezes>
        </Vegzettseg>
        <Vegzettseg ID="veg2">
            <megnevezes>Cukrász</megnevezes>
        </Vegzettseg>
        <Vegzettseg ID="veg3">
            <megnevezes>Eladó</megnevezes>
        </Vegzettseg>
        <Vegzettseg ID="veg4">
            <megnevezes>Boltvezető</megnevezes>
        </Vegzettseg>
    </Vegzettsegek>

    <PekVegzettsegek>
        <PekVegzettse szemszam="12345" vegID="veg1" />        <PekVegzettse szemszam="12345" vegID="veg1" />
        <PekVegzettse szemszam="12345" vegID="veg4" />
        <PekVegzettse szemszam="23456" vegID="veg2" />
        <PekVegzettse szemszam="23456" vegID="veg3" />
        <PekVegzettse szemszam="34567" vegID="veg1" />
        <PekVegzettse szemszam="45678" vegID="veg2" />
        <PekVegzettse szemszam="45678" vegID="veg3" />

    </PekVegzettsegek>

</root>
